Vagrant.configure(2) do |config|
  config.vm.provider "virtualbox" do |vb|
    vb.name = "dbox-gui" # Set vm name in virtualbox
    vb.customize ["modifyvm", :id, "--memory", "4096"] # Set vm memory in MB
    vb.gui = true # turn on the console gui display
  end

  config.vm.box = "ubuntu/zesty64" # Specify base image to use
  config.vm.hostname = "devbox-gui" # Set vm hostname

  # Provisioning mechanisms
  #  Use file provisioner to copy local file to vm
  config.vm.provision "file", source: "../common/screenrc", destination: "/tmp/screenrc"

  #  Use an 'inline' shell command string to install LXDE and virtualbox additions
  config.vm.provision "shell", inline: "sudo apt-get update && sudo apt-get install -y ubuntu-desktop virtualbox-guest-dkms virtualbox-guest-utils virtualbox-guest-x11"

  #  Permit anyone to start the GUI
  config.vm.provision "shell", inline: "sudo touch /etc/X11/Xwrapper.config && sudo sed -i 's/allowed_users=.*$/allowed_users=anybody/' /etc/X11/Xwrapper.config"

  #  Call a script on the vm host which executes on the vm
  config.vm.provision :shell, path: "../provisioners/devbox_env_provisioner_gui.sh"

  # Example folder syncing
  # config.vm.synced_folder "../../git", "/home/vagrant/git"

end
